# Given two strings s and t of equal length, the Hamming distance between s and
# t, denoted dH(s,t), is the number of corresponding symbols that differ in s
# and t. See Figure 2.
#
# Given: Two DNA strings s and t of equal length (not exceeding 1 kbp).
#
# Return: The Hamming distance dH(s,t).

# Sample Dataset
#
# GAGCCTACTAACGGGAT
# CATCGTAATGACGGCCT
#
# Sample Output
# 7


s1 = 'GAGCCTACTAACGGGAT'
s2 = 'CATCGTAATGACGGCCT'

def hamm_dist(s1, s2):
    assert len(s1) == len(s2), "Sequences must be of equal length"

    # non-list comprehension version:
    # hamm = 0
    # for i in range(len(s1)):
    #     hamm += (list(s1)[i] != list(s2)[i])

    hamm = [a==b for (a, b) in zip(s1, s2)].count(False)
    print(hamm)



hamm_dist(s1, s2)


s3 = 'TGAGGTTGCCTGCAATAAGATGTCCTCTCGATCGCACGGTAACTTATCACCTCGTCCGTCGCTTTGGTTGCGCACTACCTCTGTCCCGAGAATGGTCGAACACATACTGTGTCATGAACGCCCACAAGGTATTTCCGGCCGGAAAGTTCTCAATCTGTTTGATCTGAGATTGTAGCCTCTTTTTACGGCGTAGGACCCCAGAGTTCGTCTGTCGTTGACAGTGTCCACCTTCTTATGGCAGGACCATTATCTCGTAGCCATAGATGGGTAGGAAGCGATGTGACAGAGATATACTAACCTCAGGTTATGCATGAGGGCGGGGTTTTTCCGGGTTGCCCTCCTTTCTTCCATTCATTCAGGGCTTGGAACCTAGCACGCGTATTAATCCTCACTTAGTTCCTGCGTAAAAGCGTTTACTCAAAGAGAAGATTAGCTGCAGAGGAACGGTCACTGGTACGATCGCGGCCCTTTCCGTACGGTTGCGGGCCAAGGATACTCCGGCCCGTCGGTCGGGTCCCGACCGTGGTGCTAGGGCGTCAACTGAGCTAAGAAGGTGTTAGGCATTGGAACGGGGTGTCCATCAGCGCTTGGCGCAACATTGGTTTTATCGAGTTGGGACGAAGGCATCGGACATACGAGCCACTGAATTTTATTACGCCCTAGACGCATGCCATAAGGAAAGTCACATTGCAACAATGAATTCGGGCAATAGAGGCTTCGGCCACATTCGTTCGAATCCATTGACGTCATAATTGTTCCTCCTGGCGTATTTAATGGGTCCGTGACCGGGCCCAATTATGAAACGACAACGCGAGATATCTCGTACACGTGGCGGCGCAAGGACGAATTATAGCGGGATTACCGCACCGATACCAGCCCCACGTCGGCGTCGTCGACATCCAGTCGACCTGCATTACCTTAACATTTTCTGCCCGAATCTGGGAGAAATACTGTATATC'
s4 = 'TGCCGTATTGTCCAATATCATGTGCTCGGAATTTCGGGCCATCTGATCACCCCGTACTGCCGAGTTGTTTCGAAATATCCGCTAAACGACTCGGATGGGCCTCCTTCTGCGGCATGACAGTCGAAAAGGAAATGCTAGATATAGCGGGCTCATTAAGTACGGTGGGAGTTTCCATGGTATATTCACGACGTCAGCCCTCTTAGCCAGTGTGTGGGCGCCTCTTCCCGTCAAAGGTTGCCATGCCAAGTACTCTATAGCGCAAGAGGCGCTTAAAGTGTCTGGACAGAGTTCTAAAAAATTCATGTGCTGCGTGGCGGGCGTACTTTTCAGGGTCATCGGCCTTCGTTCCATTCCGTCAAGGTTAGAGCGTAGCCACCTATAGCACTCCTAACGTCACCCCTTAGTAAACCCGTCATTTTCAACAGAAACCCGAGTTCATTGGTCCGGTGCTTGGCCCTAGCGAGAACCGATACGCCAGGGATTGGGGTGAGGATAATCCGCCCTGACGAGTGTATTTCAGCCCTTCAGGAACGGGAACAAATATGAAGAGGAGGTGGAAGTTTTAGTCTCGAGTTCTCCTTGAATCTTCCGCGCAAGATTAGATCTATCCAATTGAACCTAGTTCTAGAGGTATACTGGTGACTGAGTTTCTACTCGAGGGGGACACCTGCGTACAGTATAGTTACAGTGCAACACGCAAATAGGGCAAGACACACCTCCGCAAGTATCGCCCCTCTGCGTATTAACTATATTTGCTCTTATACTCGGCGTTAATCGGGCCTGGATCGTACCCAATAAAAGGGTGACCGCATGCTATGTAGTGGAGTGAAGATGGCGTAAGTAACACAATTGACGACCCTCGGTTTTCGATATCAGCCATTCGTGGTCGTCCTTCAAAACAATCGGACGTGAACCAGCTTAACATCTTCTCCGCGTATCATAACAGAGTAGTGGTCTGC'
hamm_dist(s3, s4)