# Problem
#
# An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.
#
# Given a DNA string t
# corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u
# .
#
# Given: A DNA string t
# having length at most 1000 nt.
#
# Return: The transcribed RNA string of t
# .
# Sample Dataset
#
# GATGGAACTTGACTACGTAAATT
#
# Sample Output
#
# GAUGGAACUUGACUACGUAAAUU

s = 'GATGGAACTTGACTACGTAAATT'

def transcribe_to_RNA(s):
    x = s.replace('T', 'U')
    print(x)

transcribe_to_RNA(s)

test_string = 'TTTGACTTATTTGCACCCGACAAGTACCCGTTCCAACCCTAAATAGTCACAATGCGTTCAATTGTAATGCGAGTCAGCCTACTGCGTTTAGGACGGCGCGCCGATGGTAGCAGCATTGCAGAATATCTCAGAAGATATCTTGAACGCGAGGAGTTGGCAGCGCGTGCAGGAGCTAGTCACTTAAGCATACTGCTTTGTGATCTCTATCAATGATAGCAATTTGAGGTCCGATTCACATTCCGAATGGTCTTACGTGTCTCTAGTGATTATCGGCTTGTATTCTCTGGCTAAATCTCGATCATGTGCGGCATACACACACTTTCGGTCATGGAACAAGAACACGTAGCCTTGCCGGCAGAGCTCTCTAGCCCTGGCGTCCGATGGGTGCGATTCCCTGAGCGGTTGGTAAAAATATTGAGTTATAGCCGTTCACGGCAACCCGCGTCCGAGTCCGTCAAACCCTTCCCTGCGATAGCTGCTTAAACCGGATACCGAGAGACTGATGGTTAACACGGCCGGGCTTCGTACTGTGGTTGCCACTATCCTAGGTCCTCTGAAGCCAAAGGAGTGTGATAGCTCTTGGCTGCGCCCATTCCAAATACGTTCTCCCACTATGGCCCGTCCCCTGAGGAAGGACTCGTGAATTATCAAGTTTGATGGCTGTCGTATAATCATCCGAAGTAACCTTGGCTTCAGGATCTCTATGGCCTTGTCCCCCCTCGAACTCACCACCTGTGCCTCCCCGATACTGCAGAGTTAAACTTCCCGAGCCGGAAACCAGCCACAACAGCTAGTAGTGACTGCTCCCCTAACCAAAAGTGTCCTAGGTTGCAACGTAAGCGGACCTGAGATTAAATCAGGTAGGCCGGGTGGGTATTAGATGCAACAGCATTTCGACCAGGGATATTCTGGCCCGCCTGCGGTAGA'

transcribe_to_RNA(test_string)
